#ifndef RADAR_REG_H
#define RADAR_REG_H

#define RADAR_CMD_WRITE_DETECT_DISTANCE 0X02
#define RADAR_CMD_READ_DETECT_DISTANCE 0X03

#define RADAR_CMD_WRITE_DELAY_TIME 0X04
#define RADAR_CMD_READ_DELAY_TIME 0X05

#define RADAR_CMD_SAVE_RADAR_PARAM 0X08

#define RADAR_CMD_READ_RADAR_FUNC_ENABLE 0XD0
#define RADAR_CMD_WRITE_RADAR_FUNC_ENABLE 0XD1


#endif